
import React from 'react';

const TermsOfService: React.FC = () => {
  return (
    <div className="bg-[#fcfdff] min-h-screen pb-24">
      <div className="bg-white border-b border-gray-100 py-8 md:py-12">
        <div className="max-w-7xl mx-auto px-8">
          <h4 className="text-[10px] font-black text-[#9d7bb0] uppercase tracking-[0.4em] mb-4">Agreement</h4>
          <h1 className="text-4xl md:text-6xl font-black text-gray-900 tracking-tighter leading-none">
            Terms of Use
          </h1>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-8 mt-6 prose prose-slate max-w-none">
        <div className="bg-white p-8 md:p-12 rounded-[32px] border border-gray-100 shadow-sm space-y-10">
          <section className="space-y-4">
            <h2 className="text-xl font-black text-gray-900 uppercase tracking-tight">1. Acceptance of Terms</h2>
            <p className="text-gray-600 font-medium leading-relaxed">
              By accessing or using the Avagama AI platform, you agree to be bound by these Terms of Use and all applicable laws and regulations. If you do not agree with any of these terms, you are prohibited from using or accessing this site.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-black text-gray-900 uppercase tracking-tight">2. Use License</h2>
            <p className="text-gray-600 font-medium leading-relaxed">
              Permission is granted to temporarily access the materials (information or software) on Avagama AI's website for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer of title, and under this license you may not:
            </p>
            <ul className="list-disc pl-6 text-gray-600 font-medium space-y-2">
              <li>Modify or copy the materials;</li>
              <li>Use the materials for any commercial purpose, or for any public display;</li>
              <li>Attempt to decompile or reverse engineer any software contained on the platform;</li>
              <li>Remove any copyright or other proprietary notations from the materials.</li>
            </ul>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-black text-gray-900 uppercase tracking-tight">3. AI-Generated Content</h2>
            <p className="text-gray-600 font-medium leading-relaxed">
              The roadmaps, scores, and strategic insights provided by Avagama AI are generated by artificial intelligence. While we strive for accuracy, these outputs should be used as a guide and not as absolute financial or technical advice. Users are responsible for validating AI suggestions before implementation.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-black text-gray-900 uppercase tracking-tight">4. Account Responsibility</h2>
            <p className="text-gray-600 font-medium leading-relaxed">
              You are responsible for maintaining the confidentiality of your account and password and for restricting access to your computer. You agree to accept responsibility for all activities that occur under your account or password.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-black text-gray-900 uppercase tracking-tight">5. Limitations</h2>
            <p className="text-gray-600 font-medium leading-relaxed">
              In no event shall Avagama AI or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on Avagama AI's platform.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-black text-gray-900 uppercase tracking-tight">6. Governing Law</h2>
            <p className="text-gray-600 font-medium leading-relaxed">
              These terms and conditions are governed by and construed in accordance with the laws of the jurisdiction in which Avagama AI operates and you irrevocably submit to the exclusive jurisdiction of the courts in that State or location.
            </p>
          </section>

          <section className="pt-10 border-t border-gray-50">
            <p className="text-xs text-gray-400 font-bold uppercase tracking-widest text-center">
              © 2026 Avagama AI. All Rights Reserved.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
};

export default TermsOfService;
